language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ptpedroj/docker-react -f local.Dockerfile .

script:
  - docker container run -e CI=true ptpedroj/docker-react npm run test
